version: '3'
services:
  db:
    container_name: pg_container_fm
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - pg-dataset:/var/lib/postgresql/data

volumes:
  pg-dataset: